apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apicurio-registry-8drw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apicurio-registry-8drw
    app.kubernetes.io/part-of: apicurio-registry
  name: apicurio-registry-8drw
  namespace: rhn-support-bpimente-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: apicurio-registry-8drw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: apicurio-registry-8drw
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:193c46f03b5913c68e61984a853fbdf54ff36d1017fe71f2c774de5db9037378
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
