apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apicurio-registry-8drw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apicurio-registry-8drw
    app.kubernetes.io/part-of: apicurio-registry
  name: apicurio-registry-8drw
  namespace: rhn-support-bpimente-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: apicurio-registry-8drw
status:
  loadBalancer: {}
